<a href="https://colab.research.google.com/github/mizykk/Python-Basic/blob/master/Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Encoding  
범주형 변수 -> 연속형 변수  



In [1]:
import pandas as pd

fruit = pd.DataFrame({'name':['apple', 'banana', 'cherry', 'durian'],
                      'color':['red', 'yellow', 'red', 'green']})   #예시 데이터 생성
fruit

name   color
0   apple     red
1  banana  yellow
2  cherry     red
3  durian   green

## [pandas get_dummies()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.get_dummies.html)  
One-Hot Encoding

In [0]:
pd.get_dummies(fruit['name'])

apple  banana  cherry  durian
0      1       0       0       0
1      0       1       0       0
2      0       0       1       0
3      0       0       0       1

In [0]:
pd.get_dummies(fruit)

name_apple  name_banana  name_cherry  ...  color_green  color_red  color_yellow
0           1            0            0  ...            0          1             0
1           0            1            0  ...            0          0             1
2           0            0            1  ...            0          1             0
3           0            0            0  ...            1          0             0

[4 rows x 7 columns]

In [0]:
pd.get_dummies(fruit['name'], drop_first=True)   #N-1개 생성

banana  cherry  durian
0       0       0       0
1       1       0       0
2       0       1       0
3       0       0       1

## pandas Categorical  
Labelling

In [23]:
pd.Categorical(fruit['name']).codes   #문자열 labelling

array([0, 1, 2, 3], dtype=int8)

추가적인 것은 여기 참고 : https://datascienceschool.net/view-notebook/aa62265f02fc429aa636ef343c3b1fda/  

## [Scikit-learn LabelEncoder](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html)  
Labelling

In [0]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le.fit(fruit['name'])
le.transform(fruit['name'])

array([0, 1, 2, 3])

In [0]:
fruit['color'] = le.fit_transform(fruit['color'])   #fit + transform = fit_transform
fruit

name  color
0   apple      1
1  banana      2
2  cherry      1
3  durian      0

## [Scikit-learn One-Hot Encoder](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html)  
One-Hot Encoding  

sklearn의 OneHotEncoder 함수는 숫자형만 읽을 수 있기 때문에 문자형으로 된 변수는 먼저 labelling을 해주어야 한다.  
(pd.get_dummies 쓰는게 빠를듯🤦🏻‍♀️)

In [10]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

le = LabelEncoder()
fruit['name'] = le.fit_transform(fruit['name'])

onh = OneHotEncoder()
onh_reshaped = fruit['name'].values.reshape(-1, 1)
onh.fit_transform(onh_reshaped).toarray()

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## [Scikit-learn Categoricalencoder](https://15359-843222-gh.circle-artifacts.com/0/home/ubuntu/scikit-learn/doc/_build/html/stable/modules/generated/sklearn.preprocessing.CategoricalEncoder.html)  
: 있긴하지만 결국 내놓지 않은..🤷🏻‍♀️  
A. We don't have CategoricalEncoder (it's not included in the final release), please use *OrdinalEncoder* and *OneHotEncoder* instead.

In [0]:
pip install git+git://github.com/scikit-learn/scikit-learn.git   #굳이 사용하고 싶다면 이걸 install하면 된다.

In [0]:
pip install https://github.com/scikit-learn/scikit-learn/archive/master.zip   #이건 위에꺼보다 더 빠르다고 합니다.

In [0]:
from sklearn.preprocessing import CategoricalEncoder

ce = CategoricalEncoder()
fruit_reshaped = fruit['name'].values.reshape(-1,1)
ce.fit_transform(df_reshaped)